version: '3'

services:
    nodeapp:
        container_name: bookmark # Change this
        image: silvaej/bookmark # Change this
        build:
            dockerfile: Dockerfile.dev
            context: .
        ports:
            - '8080:8080'
        volumes:
            - '.:/usr/src/app'
            - /usr/src/app/node_modules
